/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCallPartyRouteImport } from './routes/_authenticated/call-party'
import { Route as AdminWorkspacesIndexRouteImport } from './routes/admin.workspaces.index'
import { Route as AuthenticatedSchuzkyIndexRouteImport } from './routes/_authenticated/schuzky.index'
import { Route as AdminWorkspacesIdRouteImport } from './routes/admin.workspaces.$id'
import { Route as AuthenticatedSchuzkyNovaRouteImport } from './routes/_authenticated/schuzky.nova'
import { Route as AuthenticatedSchuzkyIdRouteImport } from './routes/_authenticated/schuzky.$id'
import { Route as AuthenticatedNastaveniTymRouteImport } from './routes/_authenticated/nastaveni.tym'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCallPartyRoute = AuthenticatedCallPartyRouteImport.update({
  id: '/call-party',
  path: '/call-party',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminWorkspacesIndexRoute = AdminWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedSchuzkyIndexRoute =
  AuthenticatedSchuzkyIndexRouteImport.update({
    id: '/schuzky/',
    path: '/schuzky/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminWorkspacesIdRoute = AdminWorkspacesIdRouteImport.update({
  id: '/workspaces/$id',
  path: '/workspaces/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedSchuzkyNovaRoute =
  AuthenticatedSchuzkyNovaRouteImport.update({
    id: '/schuzky/nova',
    path: '/schuzky/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSchuzkyIdRoute = AuthenticatedSchuzkyIdRouteImport.update({
  id: '/schuzky/$id',
  path: '/schuzky/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNastaveniTymRoute =
  AuthenticatedNastaveniTymRouteImport.update({
    id: '/nastaveni/tym',
    path: '/nastaveni/tym',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/call-party': typeof AuthenticatedCallPartyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/join/$token': typeof JoinTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/nastaveni/tym': typeof AuthenticatedNastaveniTymRoute
  '/schuzky/$id': typeof AuthenticatedSchuzkyIdRoute
  '/schuzky/nova': typeof AuthenticatedSchuzkyNovaRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdRoute
  '/schuzky/': typeof AuthenticatedSchuzkyIndexRoute
  '/admin/workspaces/': typeof AdminWorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call-party': typeof AuthenticatedCallPartyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/join/$token': typeof JoinTokenRoute
  '/admin': typeof AdminIndexRoute
  '/nastaveni/tym': typeof AuthenticatedNastaveniTymRoute
  '/schuzky/$id': typeof AuthenticatedSchuzkyIdRoute
  '/schuzky/nova': typeof AuthenticatedSchuzkyNovaRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdRoute
  '/schuzky': typeof AuthenticatedSchuzkyIndexRoute
  '/admin/workspaces': typeof AdminWorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/call-party': typeof AuthenticatedCallPartyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/join/$token': typeof JoinTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/nastaveni/tym': typeof AuthenticatedNastaveniTymRoute
  '/_authenticated/schuzky/$id': typeof AuthenticatedSchuzkyIdRoute
  '/_authenticated/schuzky/nova': typeof AuthenticatedSchuzkyNovaRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdRoute
  '/_authenticated/schuzky/': typeof AuthenticatedSchuzkyIndexRoute
  '/admin/workspaces/': typeof AdminWorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/call-party'
    | '/dashboard'
    | '/settings'
    | '/setup'
    | '/admin/templates'
    | '/join/$token'
    | '/admin/'
    | '/nastaveni/tym'
    | '/schuzky/$id'
    | '/schuzky/nova'
    | '/admin/workspaces/$id'
    | '/schuzky/'
    | '/admin/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/call-party'
    | '/dashboard'
    | '/settings'
    | '/setup'
    | '/admin/templates'
    | '/join/$token'
    | '/admin'
    | '/nastaveni/tym'
    | '/schuzky/$id'
    | '/schuzky/nova'
    | '/admin/workspaces/$id'
    | '/schuzky'
    | '/admin/workspaces'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/_authenticated/call-party'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/setup'
    | '/admin/templates'
    | '/join/$token'
    | '/admin/'
    | '/_authenticated/nastaveni/tym'
    | '/_authenticated/schuzky/$id'
    | '/_authenticated/schuzky/nova'
    | '/admin/workspaces/$id'
    | '/_authenticated/schuzky/'
    | '/admin/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/call-party': {
      id: '/_authenticated/call-party'
      path: '/call-party'
      fullPath: '/call-party'
      preLoaderRoute: typeof AuthenticatedCallPartyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/workspaces/': {
      id: '/admin/workspaces/'
      path: '/workspaces'
      fullPath: '/admin/workspaces/'
      preLoaderRoute: typeof AdminWorkspacesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/schuzky/': {
      id: '/_authenticated/schuzky/'
      path: '/schuzky'
      fullPath: '/schuzky/'
      preLoaderRoute: typeof AuthenticatedSchuzkyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/workspaces/$id': {
      id: '/admin/workspaces/$id'
      path: '/workspaces/$id'
      fullPath: '/admin/workspaces/$id'
      preLoaderRoute: typeof AdminWorkspacesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/schuzky/nova': {
      id: '/_authenticated/schuzky/nova'
      path: '/schuzky/nova'
      fullPath: '/schuzky/nova'
      preLoaderRoute: typeof AuthenticatedSchuzkyNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schuzky/$id': {
      id: '/_authenticated/schuzky/$id'
      path: '/schuzky/$id'
      fullPath: '/schuzky/$id'
      preLoaderRoute: typeof AuthenticatedSchuzkyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nastaveni/tym': {
      id: '/_authenticated/nastaveni/tym'
      path: '/nastaveni/tym'
      fullPath: '/nastaveni/tym'
      preLoaderRoute: typeof AuthenticatedNastaveniTymRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCallPartyRoute: typeof AuthenticatedCallPartyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedNastaveniTymRoute: typeof AuthenticatedNastaveniTymRoute
  AuthenticatedSchuzkyIdRoute: typeof AuthenticatedSchuzkyIdRoute
  AuthenticatedSchuzkyNovaRoute: typeof AuthenticatedSchuzkyNovaRoute
  AuthenticatedSchuzkyIndexRoute: typeof AuthenticatedSchuzkyIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCallPartyRoute: AuthenticatedCallPartyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedNastaveniTymRoute: AuthenticatedNastaveniTymRoute,
  AuthenticatedSchuzkyIdRoute: AuthenticatedSchuzkyIdRoute,
  AuthenticatedSchuzkyNovaRoute: AuthenticatedSchuzkyNovaRoute,
  AuthenticatedSchuzkyIndexRoute: AuthenticatedSchuzkyIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminWorkspacesIdRoute: typeof AdminWorkspacesIdRoute
  AdminWorkspacesIndexRoute: typeof AdminWorkspacesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminWorkspacesIdRoute: AdminWorkspacesIdRoute,
  AdminWorkspacesIndexRoute: AdminWorkspacesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
